name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: '${{ secrets.CACHIX_REPO }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Run Unit tests
      run: nix develop --command bash -c "HUNTING_HAWK_SMOKE=1 pytest ."

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: nix build .#dockerStream && ./result | docker load

    - name: Build and push Docker image
      run: docker push neosloth/huntinghawk:latest

    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy
      run: flyctl deploy -a huntinghawk -i neosloth/huntinghawk:latest
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
