name: CI
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: theneosloth
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run a static type check
      run: nix develop -c mypy .
    - name: Run Unit tests
      run: nix develop -c pytest
