name: CI
on:
  pull_request:
  push:
    branches-ignore:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: ${{ secrets.CACHIX_REPO }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run a linter
      un: nix develop -c ruff .
    - name: Run a static type check
      run: nix develop -c mypy .
    - name: Run Unit tests
      run: nix develop -c pytest
